version: "3.8"

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydatabase
    ports:
      - "5434:5432"  # Пробросим порт 5434 на хосте
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:mysecretpassword@postgres:5432/mydatabase
    depends_on:
      - postgres
    networks:
      - app-network
    ports:
      - "8000:8000"


networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
