services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5434:5432"
    volumes:
      - app_pg_data:/var/lib/postgresql/data
      - app_pg_data_backups:/backups
    networks:
      - app-network

  redis:
    image: redis:7
    container_name: redis
    ports:
       - "6380:6379"
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
    env_file:
      - ${ENV_FILE}
    depends_on:
      - postgres
      - redis
    networks:
      - app-network
    ports:
      - "8001:8001"
    volumes:
      - /usr/local/flexites/projects_ext/YandexG:/app

networks:
  app-network:
    driver: bridge

volumes:
  app_pg_data:
  app_pg_data_backups:
    driver: local
