"""add visits convrate

Revision ID: 72ee1bb5936a
Revises: e482676a9f4b
Create Date: 2025-04-16 14:19:54.464230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72ee1bb5936a'
down_revision: Union[str, None] = 'e482676a9f4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal_statistics', sa.Column('conversion_rate', sa.Float(), nullable=True))
    op.add_column('goal_statistics', sa.Column('visits', sa.Integer(), nullable=True))
    op.alter_column('goal_statistics', 'conversions',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('goal_statistics', 'conversions',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('goal_statistics', 'visits')
    op.drop_column('goal_statistics', 'conversion_rate')
    # ### end Alembic commands ###
